Repository sofa-framework/BeamAdapter, pull requests merged in 2022-08, with the labels that each got.

#27 Fix draw methods in components
  src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
  src/BeamAdapter/component/engine/WireRestShape.inl
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.h
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
  src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.h
  src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
Labels: pr: fix

#30 Various cleanups
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.cpp
  src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.h
  src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.h
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
  src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.inl
  src/BeamAdapter/component/controller/AdaptiveBeamController.h
  src/BeamAdapter/component/controller/AdaptiveBeamController.inl
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
  src/BeamAdapter/component/controller/SutureController.h
  src/BeamAdapter/component/controller/SutureController.inl
  src/BeamAdapter/component/engine/SteerableCatheter.h
  src/BeamAdapter/component/engine/SteerableCatheter.inl
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.h
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.cpp
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.h
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
  src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.h
  src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
Labels: pr: clean

#41 [tests] Add SingleBeam, SingleBeamDeployment and SingleBeamDeploymentCollision to regression tests.
  examples/RegressionStateScenes.regression-tests
  examples/SingleBeam.scn
  regression/references/SingleBeam.scn.reference
  regression/references/SingleBeam.scn.reference_0_DOFs_mstate.txt.gz
  regression/references/SingleBeamDeployment.scn.reference
  regression/references/SingleBeamDeployment.scn.reference_0_DOFs Container_mstate.txt.gz
  regression/references/SingleBeamDeploymentCollision.scn.reference
  regression/references/SingleBeamDeploymentCollision.scn.reference_0_DOFs Container_mstate.txt.gz
  regression/references/SingleBeamDeploymentCollision.scn.reference_1_CollisionDOFs_mstate.txt.gz
Labels: pr: new feature

#39 Fix (some) assertions error occuring in Debug (from the 3instruments_*.scn)
  examples/3instruments_collis.scn
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
Labels: pr: fix, pr: clean

#42 [component] Factorize BeamSection structure
  CMakeLists.txt
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/utils/BeamSection.h
Labels: pr: status to review

#43 [Tests] Add more tests for AdaptiveBeamForceFieldAndMass
  BeamAdapter_test/BeamInterpolation_test.cpp
  BeamAdapter_test/component/forcefield/AdaptiveBeamForceFieldAndMassTest.cpp
Labels: pr: new feature, pr: status to review

#44 [Component] Clean WireRestShape includes and typedef and update init method
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
Labels: pr: clean, pr: status ready

#45 [Component] Clean header includes and typedef in AdaptiveBeamForceFieldAndMass
  BeamAdapter_test/BeamInterpolation_test.cpp
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.cpp
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
Labels: pr: clean, pr: status ready

#46 [Component] Clean BeamInterpolation includes and typedef
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
Labels: pr: clean, pr: status ready

#48 [Component] Factorize interpolation parameters computation between stiffness and mass computation
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
Labels: pr: clean, pr: status ready
