Repository sofa-framework/BeamAdapter, pull requests merged in 2022-10, with the labels that each got.

#60 [InterventionalRadiologyController] Rewrite method sortCurvAbs to use std sort + unique
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: clean, pr: status ready

#59 [InterventionalRadiologyController] Remove unused methods and redondant Data d_curvAbs
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: clean, pr: status ready

#68 Fix compilation of CUDA types and add float based components
  src/BeamAdapter/gpu/cuda/CudaInstantiations.cpp
Labels: pr: status to review

#64 [WireRestShape] Remove unnecessary use of Edge2QuatTopologyMapping
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
Labels: pr: clean, pr: status ready

#62 [InterventionalRadiologyController] Rewrite method interventionalRadiologyComputeSampling
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
  src/BeamAdapter/component/engine/WireRestShape.h
Labels: pr: fix, pr: clean, pr: status ready

#75 Remove dependency on Sofa.GL
  BeamAdapterConfig.cmake.in
  CMakeLists.txt
  src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
Labels: pr: clean, pr: status to review

#77 Remove useless Sofa.GL include
  src/BeamAdapter/component/constraint/ImplicitSurfaceAdaptiveConstraint.h
Labels: pr: status to review

#79 Fix timers by using ScopedAdvancedTimer
  src/BeamAdapter/component/mapping/BeamLengthMapping.inl
Labels: pr: fix, pr: status ready

#72 [InterventionalRadiologyController] Improve init checks to avoid potential crashes
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: fix

#69 [WireRestShape] Fix loading a shape from BaseLoader
  examples/Tool_from_loader.scn
  examples/mesh/key_tip.obj
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
Labels: pr: status to review
