Repository sofa-framework/BeamAdapter, pull requests merged in 2023-09, with the labels that each got.

#112 Remove UnbuiltGenericConstraintSolver files
  src/BeamAdapter/component/solver/UnbuiltGenericConstraintSolver.cpp
  src/BeamAdapter/component/solver/UnbuiltGenericConstraintSolver.h
Labels: pr: clean, pr: status to review

#102 [WireBeamInterpolation] Move ProjectionSearch into SlidingConstraint
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.h
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
Labels: pr: clean, pr: status ready

#103 [BeamInterpolation] Add method computeTransform with node indices as parameters
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamLengthConstraint.inl
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
Labels: pr: clean, pr: status ready

#105 [InterventionalRadiologyController] Split and rename methods sortCurvAbs and interventionalRadiologyComputeSampling for more clarity
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: clean, pr: status ready

#107 [InterventionalRadiologyController] Small Fix to avoid adding 0 curvAbs per deployed device
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: fix, pr: status ready

#104 Remove code linked to brokenIn2
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: clean, pr: status ready
