Repository sofa-framework/BeamAdapter, pull requests merged in 2023-05, with the labels that each got.

#93 Replace deprecated constructor of OptionsGroup
  src/BeamAdapter/component/BeamInterpolation.inl
Labels: pr: fix, pr: status ready

#88 [InterventionalRadiologyController] Revert sampling change of behaviour
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: fix, pr: status ready

#80 Restore BeamLengthMapping
  BeamAdapter_test/CMakeLists.txt
  BeamAdapter_test/component/mapping/BeamLengthMappingTest.cpp
  BeamAdapter_test/component/mapping/MappingTest.cmake
  CMakeLists.txt
  src/BeamAdapter/component/mapping/BeamLengthMapping.cpp
  src/BeamAdapter/component/mapping/BeamLengthMapping.h
  src/BeamAdapter/component/mapping/BeamLengthMapping.inl
  src/BeamAdapter/component/mapping/Mapping.cmake
Labels: pr: new feature, pr: status ready

#67 [Tests] Add tests on WireRestShape component
  BeamAdapter_test/CMakeLists.txt
  BeamAdapter_test/component/controller/InterventionalRadiologyController_test.cpp
  BeamAdapter_test/component/model/WireRestShape_test.cpp
  src/BeamAdapter/component/BeamInterpolation.cpp
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
  src/BeamAdapter/component/engine/WireRestShape.cpp
Labels: pr: new feature, pr: status to review

#94 [MultiAdaptiveBeamMapping] Fix potential bug when removing baseEdge
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
  src/BeamAdapter/component/mapping/MultiAdaptiveBeamMapping.inl
Labels: pr: fix, pr: status to review

#95 Disable BeamLengthMapping test
  BeamAdapter_test/component/mapping/BeamLengthMappingTest.cpp
Labels: pr: clean, pr: status to review
