Repository sofa-framework/BeamAdapter, pull requests merged in 2023-11, with the labels that each got.

#116 [WireRestShape] Clean code related to brokenIn2 and EdgeSetTopologyModifier
  BeamAdapter_test/component/model/WireRestShape_test.cpp
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
Labels: pr: clean, pr: status to review

#115 [forcefield] updates AdaptiveBeamForceFieldAndMass with the new matrix assembly API
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
Labels: enhancement, pr: status to review

#111 [BeamAdapterActionController] Update Actions reading/writting and IRCtrl control
  src/BeamAdapter/component/controller/BeamAdapterActionController.inl
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: fix, pr: status to review
