Repository sofa-framework/BeamAdapter, pull requests merged in 2024-02, with the labels that each got.

#132 Move cuda instantiations in a plugin
  CMakeLists.txt
  extensions/CUDA/BeamAdapter.CUDAConfig.cmake.in
  extensions/CUDA/CMakeLists.txt
  extensions/CUDA/src/BeamAdapter/CUDA/CudaInstantiations.cpp
  extensions/CUDA/src/BeamAdapter/CUDA/config.h.in
  extensions/CUDA/src/BeamAdapter/CUDA/init.cpp
  extensions/CUDA/src/BeamAdapter/CUDA/init.h
Labels: pr: status to review

#133 Initialize SofaCUDA
  extensions/CUDA/src/BeamAdapter/CUDA/init.cpp
Labels: pr: status ready

#136 Fix warnings due to depreciation of header FixedConstraint.h
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.inl
  src/BeamAdapter/component/controller/AdaptiveBeamController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
Labels: pr: clean, pr: status to review
