Repository sofa-framework/BeamAdapter, pull requests merged in 2024-01, with the labels that each got.

#123 [Documentation] Update Readme and regroup all documentation in md files
  README.md
  doc/BeamAdapter.bib
  doc/BeamAdapter.pdf
  doc/BeamAdapter.tex
  doc/README.md
  doc/TodoList.rtf
  doc/UMLBeamAdapter.png
  doc/UMLBeamAdapter.ps
  doc/docs/Matrix.pdf
  doc/docs/examples.md
  doc/docs/implementation.md
  doc/docs/limitation.md
  doc/docs/modeling.md
  doc/modeling/.gitkeep
  doc/modeling/BeamFrames.jpg
  doc/modeling/BeamMapping.jpg
  doc/modeling/BeamModeling.jpg
  doc/modeling/CatheterModeling.jpg
  doc/modeling/Matrix.jpg
  doc/modeling/Matrix_param.jpg
  doc/modeling/implementation.md
  doc/modeling/theory.md
  doc/screenshots/AdaptiveBeamMapping.png
  doc/screenshots/WireSections.png
Labels: documentation, pr: clean, pr: status to review

#125 Add relative path to references files into regression-tests files
  examples/RegressionStateScenes.regression-tests
Labels: pr: fix, pr: status ready

#127 Fix doc links using absolute path
  doc/Doxyfile
  doc/README.md
Labels: documentation, pr: fix, pr: status to review

#129 Remove standard output messages
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
  src/BeamAdapter/component/mapping/BeamLengthMapping.h
  src/BeamAdapter/component/mapping/BeamLengthMapping.inl
Labels: pr: clean, pr: status ready

#126 [scenes] Fix python scenes using the new Section Material components
  examples/python3/Cochlear-Implant-Insertion/Scene_Cochlea.py
  examples/python3/SingleBeam.py
  examples/python3/SingleBeamDeployment.py
  examples/python3/SingleBeamDeploymentCollision.py
Labels: pr: fix, pr: status to review

#130 Fix minor things in a failing test
  BeamAdapter_test/component/mapping/BeamLengthMappingTest.cpp
Labels: pr: fix, pr: status to review
