Repository sofa-framework/BeamAdapter, pull requests merged in 2024-07, with the labels that each got.

#151 WireRestShape: getBeamSection() must return a const ref in any case
  src/BeamAdapter/component/engine/WireRestShape.inl
  src/BeamAdapter/utils/BeamSection.h
Labels: pr: fix, pr: status ready

#153 [scenes] Fix scene warnings in xml and python
  examples/3instruments.scn
  examples/3instruments_collis.scn
  examples/AdaptiveBeamController.scn
  examples/AdaptiveBeamMapping.scn
  examples/SingleBeam.scn
  examples/SingleBeamDeployment.scn
  examples/SingleBeamDeploymentCollision.scn
  examples/Tool_from_loader.scn
  examples/python3/Cochlear-Implant-Insertion/Scene_Cochlea.py
  examples/python3/SingleBeamDeployment.py
  examples/python3/SingleBeamDeploymentCollision.py
Labels: pr: fix, pr: clean, pr: status to review

#154 [src] Fix AdaptiveBeamMapping mapping at init with none deployed beam
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
Labels: pr: fix, pr: status ready

#155 [src] Update RodSection, WireRestShape and All BeamInterpolation to correctly redirect the getters to the Data
  examples/3instruments.scn
  examples/3instruments_collis.scn
  examples/SingleBeamDeployment.scn
  examples/SingleBeamDeploymentCollision.scn
  src/BeamAdapter/component/BaseBeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.h
  src/BeamAdapter/component/forcefield/AdaptiveInflatableBeamForceField.inl
  src/BeamAdapter/component/model/BaseRodSectionMaterial.h
  src/BeamAdapter/component/model/BaseRodSectionMaterial.inl
Labels: pr: clean, pr: status ready
