Repository sofa-framework/BeamAdapter, pull requests merged in 2024-05, with the labels that each got.

#145 Fix crash if pointer is null
  src/BeamAdapter/component/WireBeamInterpolation.inl
Labels: pr: fix, pr: status to review

#146 Remove old deprecation
  src/BeamAdapter/component/constraint/AdaptiveBeamSlidingConstraint.cpp
Labels: pr: clean, pr: status ready

#124 Example: apply SOFA's fix on TopologicalMapping
  examples/3instruments_collis.scn
Labels: enhancement, pr: new feature, pr: status ready

#147 [Interpolation] Add BaseBeamInterpolation class to gather all methods linked to interpolation
  CMakeLists.txt
  examples/3instruments_collis.scn
  src/BeamAdapter/component/BaseBeamInterpolation.cpp
  src/BeamAdapter/component/BaseBeamInterpolation.h
  src/BeamAdapter/component/BaseBeamInterpolation.inl
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
  src/BeamAdapter/component/engine/WireRestShape.h
  src/BeamAdapter/component/engine/WireRestShape.inl
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.h
  src/BeamAdapter/component/mapping/AdaptiveBeamMapping.inl
  src/BeamAdapter/component/model/BaseRodSectionMaterial.h
  src/BeamAdapter/component/model/BaseRodSectionMaterial.inl
Labels: pr: clean, pr: status to review
