Repository sofa-framework/BeamAdapter, pull requests merged in 2025-05, with the labels that each got.

#179 [Scenes] Fix runtime warnings, and consistent behavior between python and xml
  examples/3instruments.scn
  examples/3instruments_collis.scn
  examples/SingleBeamDeployment.scn
  examples/SingleBeamDeploymentCollision.scn
  examples/Tool_from_loader.scn
  examples/python3/SingleBeamDeployment.py
  examples/python3/SingleBeamDeploymentCollision.py
Labels: pr: clean, pr: status ready

#180 Add more regression tests
  .github/workflows/ci.yml
  examples/3instruments_collis.scn
  examples/RegressionStateScenes.regression-tests
  examples/SingleBeamDeployment.scn
  examples/SingleBeamDeploymentCollision.scn
  examples/python3/RegressionStateScenes.regression-tests
  regression/references/3instruments.scn.reference
  regression/references/3instruments.scn.reference_0_DOFs_mstate.txt.gz
  regression/references/3instruments.scn.reference_1_Quads_mstate.txt.gz
  regression/references/3instruments.scn.reference_2_Quads_mstate.txt.gz
  regression/references/3instruments.scn.reference_3_Quads_mstate.txt.gz
  regression/references/3instruments_collis.scn.reference_0_DOFs_mstate.txt.gz
  regression/references/3instruments_collis.scn.reference_1_CollisionDOFs_mstate.txt.gz
  regression/references/3instruments_collis.scn.reference_2_Quads_mstate.txt.gz
  regression/references/3instruments_collis.scn.reference_3_Quads_mstate.txt.gz
  regression/references/3instruments_collis.scn.reference_4_Quads_mstate.txt.gz
  regression/references/SingleBeam.py.reference
  regression/references/SingleBeam.py.reference_0_DOFs_mstate.txt.gz
  regression/references/SingleBeamDeployment.py.reference
  regression/references/SingleBeamDeployment.py.reference_0_DOFs Container_mstate.txt.gz
  regression/references/SingleBeamDeployment.scn.reference_0_DOFs Container_mstate.txt.gz
  regression/references/SingleBeamDeploymentCollision.py.reference
  regression/references/SingleBeamDeploymentCollision.py.reference_0_DOFs_mstate.txt.gz
  regression/references/SingleBeamDeploymentCollision.py.reference_1_CollisionDOFs_mstate.txt.gz
  regression/references/SingleBeamDeploymentCollision.scn.reference_0_DOFs Container_mstate.txt.gz
  regression/references/SingleBeamDeploymentCollision.scn.reference_1_CollisionDOFs_mstate.txt.gz
  regression/references/Tool_from_loader.scn.reference
  regression/references/Tool_from_loader.scn.reference_0_Instrument_DOFs_mstate.txt.gz
  regression/references/Tool_from_loader.scn.reference_1_dof_visual_GC_mstate.txt.gz
Labels: pr: clean, pr: status ready

#181 [IRC] Fix things about xTips
  examples/SingleBeamDeployment.scn
  examples/SingleBeamDeploymentCollision.scn
  examples/Tool_from_loader.scn
  examples/python3/SingleBeamDeployment.py
  examples/python3/SingleBeamDeploymentCollision.py
  src/BeamAdapter/component/controller/InterventionalRadiologyController.h
  src/BeamAdapter/component/controller/InterventionalRadiologyController.inl
Labels: pr: fix, pr: clean, pr: status ready

#184 [Interpolations] Fix init stage
  src/BeamAdapter/component/BaseBeamInterpolation.h
  src/BeamAdapter/component/BaseBeamInterpolation.inl
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.inl
Labels: pr: fix, pr: clean, pr: status ready

#185 [Interpolations] Remove raw ptr for mstate and topology
  src/BeamAdapter/component/BaseBeamInterpolation.h
  src/BeamAdapter/component/BaseBeamInterpolation.inl
  src/BeamAdapter/component/BeamInterpolation.h
  src/BeamAdapter/component/BeamInterpolation.inl
  src/BeamAdapter/component/WireBeamInterpolation.h
  src/BeamAdapter/component/WireBeamInterpolation.inl
Labels: pr: clean, pr: status ready, pr: breaking

#191 Add 'notify dashboard' step to CI
  .github/workflows/ci.yml
Labels: pr: status to review

#192 Remove quote to send real boolean
  .github/workflows/ci.yml
Labels: pr: status ready

#187 Cleaning of AdaptiveBeamForceFieldAndMass
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.h
  src/BeamAdapter/component/forcefield/AdaptiveBeamForceFieldAndMass.inl
Labels: pr: clean, pr: status to review, pr: status ready, pr: breaking
